// DTG shared section archetype kit (Phase A scaffold — masterbook / VISUAL-ARCHITECTURE-PLAN §7, §12).
// Surface-aware, token-driven, data-prop building blocks. Not yet adopted by pages;
// pages migrate onto these incrementally in later phases (do not rebuild pages in Phase A).
export { Surface } from "./Surface";
export type { SurfaceProps, SurfaceVariant } from "./Surface";
export { SectionHero } from "./SectionHero";
export type { SectionHeroProps, SectionHeroVariant } from "./SectionHero";
export { StatementBand } from "./StatementBand";
export type { StatementBandProps } from "./StatementBand";
export { EditorialSplit } from "./EditorialSplit";
export type { EditorialSplitProps } from "./EditorialSplit";
export { ValueGrid } from "./ValueGrid";
export type { ValueGridProps, ValueGridItem } from "./ValueGrid";
export { MetricsBand } from "./MetricsBand";
export type { MetricsBandProps, Metric } from "./MetricsBand";
export { ProcessSteps } from "./ProcessSteps";
export type { ProcessStepsProps, ProcessStep } from "./ProcessSteps";
export { FocusModule } from "./FocusModule";
export type { FocusModuleProps } from "./FocusModule";
export { ProcessSpine } from "./ProcessSpine";
export type { ProcessSpineProps, SpineNode } from "./ProcessSpine";
export { FaqAccordion } from "./FaqAccordion";
export type { FaqAccordionProps, FaqItem } from "./FaqAccordion";
export { ProfileCard } from "./ProfileCard";
export type { ProfileCardProps } from "./ProfileCard";
export { CTA } from "./CTA";
export type { CTAProps } from "./CTA";
export { Matrix } from "./Matrix";
export type { MatrixProps, MatrixRow, MatrixCell, MatrixMark } from "./Matrix";
export { Tabs } from "./Tabs";
export type { TabsProps, TabItem } from "./Tabs";
export { SectionReveals } from "./SectionReveals";
export { ServicePage } from "./ServicePage";
export type { ServiceContent } from "./ServicePage";
