import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, BarChart3, BellRing, Building2, Mountain, Network, RadioTower, Satellite, ShieldCheck, Waves } from "lucide-react";
import { FocusVision, MonitoringCentreVisual, Workflow } from "@/components/geotechnical";
import { CTA, InlineLink, Reveal, SectionLabel } from "@/components/ui";

const sectors=[
 ["Mining","Open pit slopes / Underground / Tailings storage facilities","/images/sector-mining.png",Mountain],
 ["Infrastructure","Rail / Ports / Roads / Dams","/images/sector-infrastructure.png",Building2],
 ["Natural Hazards","Landslides / Rockfall / Regional deformation","/images/sector-hazards.png",Waves],
];
const projects=[
 ["Greatland Gold","Telfer Mine, Western Australia","Integrated geotechnical monitoring and intelligence support.","GroundProbe SSR / Catalyst Earth InSAR / Trimble Prisms"],
 ["Harmony Gold","Hidden Valley Mine, Papua New Guinea","Remote geotechnical monitoring and operational support.","GroundProbe SSR"],
 ["Golden Energy Mines","PT Borneo Indobara, Indonesia","Radar monitoring support and operational monitoring services.","CHCNAV PS-2000 Radar"],
 ["Rain Group","PT Insani Baraperkasa, Indonesia","Radar monitoring support and operational monitoring services.","CHCNAV PS-2000 Radar"],
];
const whyDtg=[
 ["Australian Technical Leadership",ShieldCheck],["Indonesian Monitoring Operations",Building2],["Vendor Agnostic Approach",Network],
 ["Multi-Sensor Expertise",RadioTower],["Operational Intelligence",BarChart3],["24/7 Monitoring Support",BellRing],
];

export default function Home(){return <main>
 <section className="relative min-h-screen overflow-hidden"><Image src="/images/dtg-hero-geotechnical-intelligence.png" fill priority alt="Open pit mine with geotechnical intelligence overlays" className="object-cover opacity-70"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#04070Af7_0%,#04070Ac2_50%,#04070A44_100%)]"/><div className="absolute inset-0 bg-[linear-gradient(0deg,#04070A_0%,transparent_48%)]"/><div className="absolute right-[12%] top-[20%] h-[460px] w-[460px] rounded-full border border-[#7BA9C733]"><div className="scan"/></div><svg className="hero-contours absolute right-[3%] top-[16%] hidden h-[58%] w-[62%] opacity-55 md:block" viewBox="0 0 900 520" fill="none" aria-hidden="true"><path d="M40 394C164 335 214 292 322 292C451 292 484 166 628 166C723 166 779 204 864 116" stroke="#7BA9C7" strokeOpacity=".36"/><path d="M66 429C196 374 243 332 350 332C493 332 529 210 651 210C746 210 806 242 885 163" stroke="#7BA9C7" strokeOpacity=".2"/><path d="M121 462C231 414 281 378 389 378C536 378 573 255 691 255C767 255 827 283 899 220" stroke="#C89B5A" strokeOpacity=".24"/></svg><div className="hero-node absolute right-[25%] top-[36%] h-2.5 w-2.5 rounded-full border border-[#7BA9C7] bg-[#7BA9C777]"/><div className="hero-node absolute right-[37%] top-[48%] h-2 w-2 rounded-full bg-[#C89B5A]" style={{animationDelay:"1.1s"}}/><div className="hero-node absolute right-[17%] top-[57%] h-2 w-2 rounded-full bg-[#7BA9C7]" style={{animationDelay:"2s"}}/><div className="hero-vector absolute right-[29%] top-[43%] h-px w-16 rotate-[-26deg] bg-[#7BA9C7aa]"/><div className="hero-vector absolute right-[19%] top-[53%] h-px w-12 rotate-[18deg] bg-[#C89B5A88]" style={{animationDelay:"1.4s"}}/>
 <div className="shell relative flex min-h-screen flex-col justify-end pb-12 pt-32"><Reveal><p className="eyebrow">Geotechnical Intelligence Company</p><h1 className="display mt-7 max-w-[1060px]">Geotechnical Foresight.<br/><span className="text-[#7BA9C7]">Driven by Intelligence.</span></h1><p className="subhead mt-6 max-w-xl">Monitoring, interpretation and decision support for mining and critical infrastructure.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/#capabilities" className="button">Explore Capabilities <ArrowUpRight size={13}/></Link><Link href="/contact" className="button">Initiate Briefing</Link></div></Reveal><div className="mt-12 flex items-end justify-between border-t hairline pt-4 font-mono text-[9px] uppercase tracking-[.18em] text-[#96A8AD]"><span>Monitor / Interpret / Act</span><span className="flex items-center gap-2">Explore <ArrowDown size={13}/></span></div></div></section>

 <section id="capabilities" className="border-b hairline bg-[#04070A] py-16 md:py-20"><div className="shell"><SectionLabel index="01">What we do</SectionLabel><Reveal><h2 className="headline max-w-4xl">From ground movement to operational action.</h2></Reveal><div className="mt-10"><Workflow/></div></div></section>

 <section className="light-section border-b hairline py-20 md:py-24"><div className="shell"><SectionLabel index="02">Who we serve</SectionLabel><Reveal><h2 className="headline max-w-4xl">Intelligence for critical ground conditions.</h2></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-3">{sectors.map(([title,body,src,Icon])=><Reveal className="group relative min-h-[390px] overflow-hidden border border-[#0E3A4544]" key={title as string}><Image src={src as string} alt={title as string} fill className="object-cover opacity-78 transition duration-700 group-hover:scale-105 group-hover:opacity-95"/><div className="absolute inset-0 bg-gradient-to-t from-[#071218ee] via-[#07121855] to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><Icon size={18} className="text-[#7BA9C7]"/><h3 className="mt-5 text-3xl tracking-[-.06em] text-white">{title as string}</h3><p className="mt-3 text-[10px] uppercase leading-5 tracking-[.16em] text-[#D5E0E4]">{body as string}</p></div></Reveal>)}</div></div></section>

 <section className="border-b hairline bg-[#04070A] py-20 md:py-24"><div className="shell grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><SectionLabel index="03">Monitoring centre</SectionLabel><Reveal><h2 className="headline">Remote intelligence. Engineering context.</h2><p className="subhead mt-5 max-w-lg">Observe deformation. Interpret movement. Escalate clearly.</p></Reveal></div><Reveal delay={.1}><MonitoringCentreVisual/></Reveal></div></section>

 <section className="petroleum-section border-b hairline py-20 md:py-24"><div className="shell"><div className="flex flex-wrap items-end justify-between gap-5"><div><SectionLabel index="04">Selected Operations</SectionLabel><h2 className="headline">Operational experience.</h2></div><InlineLink href="/operations">View selected operations</InlineLink></div><div className="mt-10 border-t hairline">{projects.map(([name,place,scope,tech],i)=><Reveal className="grid gap-4 border-b hairline py-6 transition hover:bg-[#C89B5A0c] md:grid-cols-[52px_1fr_1.1fr_1fr]" key={name}><span className="font-mono text-[10px] text-[#C89B5A]">0{i+1}</span><div><h3 className="text-2xl tracking-[-.055em]">{name}</h3><p className="eyebrow mt-2">{place}</p></div><p className="body-copy">{scope}</p><p className="text-xs leading-6 text-[#D5E0E4]">{tech}</p></Reveal>)}</div></div></section>

 <section className="light-section border-b hairline py-20 md:py-24"><div className="shell"><SectionLabel index="05">Why Digital Twin Geotechnical?</SectionLabel><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><Reveal><h2 className="headline max-w-4xl">A digital twin is only as reliable as the physical data that feeds it.</h2></Reveal><Reveal delay={.08}><p className="subhead max-w-xl">DTG connects reliable monitoring, engineering interpretation and operational decisions.</p></Reveal></div><div className="mt-10 grid gap-px bg-[#0E3A4533] md:grid-cols-3">{[["Physical Twin","Reliable data.",RadioTower],["Digital Twin","Integrated intelligence.",Satellite],["Operational Twin","Actionable decisions.",ShieldCheck]].map(([title,body,Icon])=><div className="light-card border p-6" key={title as string}><Icon size={18} className="text-[#0E3A45]"/><h3 className="mt-10 text-3xl tracking-[-.06em] text-[#102127]">{title as string}</h3><p className="body-copy mt-3">{body as string}</p></div>)}</div></div></section>

 <section className="petroleum-section border-b hairline py-20 md:py-24"><div className="shell"><SectionLabel index="06">Why DTG</SectionLabel><Reveal><h2 className="headline max-w-4xl">Technical depth. Regional operations. Independent thinking.</h2></Reveal><div className="mt-10 grid gap-x-8 border-t hairline md:grid-cols-2 lg:grid-cols-3">{whyDtg.map(([title,Icon])=><div className="flex items-center gap-4 border-b hairline py-5" key={title as string}><Icon size={17} className="shrink-0 text-[#C89B5A]"/><h3 className="text-lg tracking-[-.035em]">{title as string}</h3></div>)}</div></div></section>

 <section className="grid-bg grid-drift border-b hairline bg-[#04070A] py-20 md:py-24"><div className="shell"><div className="flex flex-wrap items-center justify-between gap-4"><SectionLabel index="07">DTG Focus</SectionLabel><span className="border border-[#0E3A4566] bg-[#0E3A4533] px-3 py-2 text-[9px] uppercase tracking-[.16em] text-[#7BA9C7]">Future Platform Vision - Currently Under Development</span></div><Reveal><h2 className="headline max-w-4xl">One future intelligence layer.</h2><p className="subhead mt-5 max-w-2xl">Monitoring systems, Earth Observation and engineering context. Unified for interpretation and decision support.</p></Reveal><Reveal className="mt-10"><FocusVision/></Reveal><InlineLink href="/focus">Explore the vision</InlineLink></div></section>
 <CTA/>
 </main>}
