import Image from "next/image";
import { Building2, CircleGauge, Globe2, RadioTower, ShieldCheck, UserRound } from "lucide-react";
import { renderTrademarkText } from "@/components/brand";
import { CTA, PageHero, Reveal, SectionLabel } from "@/components/ui";
const model=[["Australian Leadership","Technical governance, client leadership and geotechnical interpretation.",Building2],["Indonesian Operations","Regional monitoring capability supporting continuous remote workflows.",CircleGauge],["Global Delivery","Scalable operational support for mining and critical infrastructure.",Globe2]];
const timeline=[["2015","Remote monitoring foundation","Development of geotechnical remote monitoring workflows for active mine operations."],["2018","Operational scale","Expanded radar monitoring, reporting and alert escalation across complex mining environments."],["2021","Regional capability","Monitoring-centre experience strengthened across Australian and Indonesian operations."],["2024","DTG established","An independent monitoring, analytics, governance and decision-support business built around integrated data, interpretation and action."],["Future","DTG Focus™ development","A future operational framework for unified monitoring, Earth Observation, analytics, governance and decision support."]];
const peter=["20+ years mining geotechnical experience","Master of Engineering Science (Mining Geomechanics)","Bachelor of Science, University of Queensland (Exploration Geophysics and Geology)","Rock Mechanics","Geotechnical Monitoring","Executive Senior Management","Founder of Digital Twin Geotechnical","Pioneer of remote geotechnical monitoring services"];
const mark=["20+ years mining industry experience","Masters Economic Geology","Masters Civil Engineering","First Class Honours Geology","Economic and Structural Geology","Geotechnical studies","Operational consulting","Mining leadership","Structural interpretation","Rock mass characterisation","Geotechnical inputs for mine design and stability decisions"];
export default function Leadership(){return <main><PageHero kicker="Leadership / Capability" index="03" title="Operational depth. Built to scale." body="DTG combines senior mining expertise, geotechnical monitoring experience and a global delivery model."/>
<section className="shell py-20 md:py-24"><SectionLabel>Operating model</SectionLabel><div className="grid gap-px bg-[#073F4A24] md:grid-cols-3">{model.map(([title,body,Icon])=><Reveal className="bg-[#0E1823] p-6" key={title as string}><Icon size={18} className="text-[#9CB6C2]"/><h2 className="mt-12 text-3xl tracking-[-.065em]">{title as string}</h2><p className="body-copy mt-4">{body as string}</p></Reveal>)}</div></section>
<section className="border-y hairline bg-[#0E1823] py-20 md:py-24"><div className="shell"><SectionLabel>Executive leadership</SectionLabel><div className="grid gap-4 lg:grid-cols-[1.18fr_.82fr]"><ExecutiveProfile index="01" name="Peter Saunders" role="Founder / Director" intro="Peter is DTG's founder and principal geotechnical monitoring leader. His background spans mining geomechanics, remote monitoring operations and executive technical leadership." highlights={peter} image="/images/peter-saunders-portrait.png" primary/><ExecutiveProfile index="02" name="Mark Burdett" role="DTG Director" intro="Economic and structural geology, geotechnical studies and operational mining insight." highlights={mark} image="/images/mark-burdett-portrait.png"/></div></div></section>
<section className="grid-bg grid-drift border-b hairline py-20 md:py-24"><div className="shell grid gap-10 lg:grid-cols-[.32fr_.68fr]"><div><SectionLabel>Operational foundation</SectionLabel><UserRound className="mt-10 text-[#9CB6C2]" size={24}/><p className="eyebrow mt-5">Peter Saunders</p><p className="mt-3 text-sm text-[#9CB6C2]">Founder / Director</p><p className="body-copy mt-6 max-w-sm">Peter Saunders pioneered and developed GroundProbe&apos;s geotechnical remote monitoring service from 2015-2024. DTG extends that operational foundation into an independent model for integrated monitoring, governance and decision support.</p></div><Reveal><h2 className="headline">A decade of monitoring operations. A broader decision-support business.</h2><div className="mt-10 border-t hairline">{timeline.map(([year,title,body])=><div className="grid gap-3 border-b hairline py-5 md:grid-cols-[90px_180px_1fr]" key={year}><span className="font-mono text-sm text-[#9CB6C2]">{year}</span><strong className="text-sm font-normal text-[#F3F5F4]">{renderTrademarkText(title)}</strong><p className="text-sm leading-6 text-[#9CB6C2]">{renderTrademarkText(body)}</p></div>)}</div></Reveal></div></section>
<section className="shell py-20 md:py-24"><SectionLabel>Monitoring background</SectionLabel><div className="grid gap-px bg-[#073F4A24] md:grid-cols-3">{[["Slope stability monitoring","Radar monitoring and displacement tracking for active mine slopes.",RadioTower],["Alerting and escalation","Structured operational workflows supporting TARP response.",ShieldCheck],["Multi-sensor interpretation","Engineering context across radar, GNSS, InSAR and prism inputs.",CircleGauge]].map(([title,body,Icon])=><div className="bg-[#0E1823] p-6" key={title as string}><Icon size={17} className="text-[#9CB6C2]"/><h3 className="mt-10 text-2xl tracking-[-.05em]">{title as string}</h3><p className="body-copy mt-4">{body as string}</p></div>)}</div></section><CTA/></main>}
function ExecutiveProfile({index,name,role,intro,highlights,image,primary=false}:{index:string,name:string,role:string,intro:string,highlights:string[],image:string,primary?:boolean}){return <Reveal className={`relative overflow-hidden border hairline bg-[#0E1823] p-6 md:p-7 ${primary?"lg:min-h-[570px] lg:p-8":"lg:mt-10 lg:min-h-[530px]"}`}><div className="flex items-center justify-between"><span className="font-mono text-[10px] tracking-[.16em] text-[#9CB6C2]">{index} / EXECUTIVE PROFILE</span>{primary&&<span className="border border-[#073F4A66] bg-[#073F4A18] px-3 py-2 text-[9px] uppercase tracking-[.16em] text-[#D79A2B]">Founder</span>}</div><div className="relative mt-7 aspect-[1.35/1] overflow-hidden border hairline bg-[#08111A] sm:aspect-[1.7/1] lg:aspect-[1.92/1]"><Image src={image} alt={`${name}, ${role} of Digital Twin Geotechnical`} fill priority={primary} sizes={primary?"(max-width: 1024px) 100vw, 58vw":"(max-width: 1024px) 100vw, 40vw"} className={`object-cover saturate-[.72] contrast-[1.04] brightness-[.82] ${primary?"object-[center_24%]":"object-[center_38%]"}`}/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,17,26,.08),rgba(11,61,83,.13))]"/><div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-[#0E1823] to-transparent"/></div><p className="eyebrow mt-6">{role}</p><h2 className={`${primary?"text-5xl":"text-4xl"} mt-3 tracking-[-.075em]`}>{name}</h2><p className="body-copy mt-5 max-w-2xl">{intro}</p><div className="mt-7 grid gap-2 border-t hairline pt-5 sm:grid-cols-2">{highlights.map((highlight)=><div className="flex gap-3 border-b hairline py-3 text-sm leading-5 text-[#F3F5F4]" key={highlight}><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#D79A2B]"/>{highlight}</div>)}</div></Reveal>}
